a = input('digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ' ,a.isnumeric())
print('É alfabético? ',a.isalpha())
print('É Alfanumérico? ', a.isalnum())
print('É um digito?  ', a.isdigit())